name: Deploy Azure resources

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure PowerShell
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Set up Azure PowerShell module
      uses: azure/powershell@v1
      with:
        azPSVersion: latest
        inlineScript: |
            ./scripts/Deploy-Resources.ps1 -ResourceGroupName "Bicep-Workshop-WRO"
